/*
 *  TripleBoardByRectangles.java
 *
 *  chess383 is a collection of chess related utilities.
 *  Copyright (C) 2015 - 2021 Jörg Dippel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package chess383.graph.board;

import java.util.List;

import chess383.ColorEnum;
import chess383.ICoordinate;
import chess383.graph.direction.Direction;
import chess383.graph.line.*;

/**
 * Provides locations on a bundle of lines for a board for three players: rectangles within a hexagon.
 *
 * @author    Jörg Dippel
 * @version   February 2021
 *
 */
public class TripleBoardByRectangles extends LineBundle {
    
    private final static Direction DIRECTED_WHITE_BLACK = Direction.createUnidirectionalDirection( ColorEnum.WHITE, ColorEnum.BLACK );
    private final static Direction DIRECTED_WHITE_RED =   Direction.createUnidirectionalDirection( ColorEnum.WHITE, ColorEnum.RED );
    private final static Direction DIRECTED_BLACK_RED =   Direction.createUnidirectionalDirection( ColorEnum.BLACK, ColorEnum.RED );
    
    static private final TripleBoardByRectangles singleton = new TripleBoardByRectangles();
    static public ICoordinate getInstance() { return singleton; }
    static public List<LineOfLocations> getStaticBundle() { return TripleBoardByRectangles.bundle; }
    
    public List<LineOfLocations> getBundle() { return getStaticBundle(); }
       
    private TripleBoardByRectangles( ) {}

    /** ------------------------------------------------------- */
    
    //  final int NUMBER_OF_LINES = 407;
    static private final List<LineOfLocations> bundle = List.of(

        // createFileLine( VERTICAL, value )

            UndirectedRowsLine.createLine(           "a1 b1 c1 d1 e1 f1 g1 h1" ),
            UndirectedRowsLine.createReversedLine(   "a1 b1 c1 d1 e1 f1 g1 h1" ),
            UndirectedRowsLine.createLine(           "a2 b2 c2 d2 e2 f2 g2 h2" ),
            UndirectedRowsLine.createReversedLine(   "a2 b2 c2 d2 e2 f2 g2 h2" ),
            UndirectedRowsLine.createLine(           "a3 b3 c3 d3 e3 f3 g3 h3" ),
            UndirectedRowsLine.createReversedLine(   "a3 b3 c3 d3 e3 f3 g3 h3" ),
            UndirectedRowsLine.createLine(           "a4 b4 c4 d4 e4 f4 g4 h4" ),
            UndirectedRowsLine.createReversedLine(   "a4 b4 c4 d4 e4 f4 g4 h4" ),

            UndirectedRowsLine.createLine(           "a8 b8 c8 d8 i8 j8 k8 l8" ),
            UndirectedRowsLine.createReversedLine(   "a8 b8 c8 d8 i8 j8 k8 l8" ),
            UndirectedRowsLine.createLine(           "a7 b7 c7 d7 i7 j7 k7 l7" ),
            UndirectedRowsLine.createReversedLine(   "a7 b7 c7 d7 i7 j7 k7 l7" ),
            UndirectedRowsLine.createLine(           "a6 b6 c6 d6 i6 j6 k6 l6" ),
            UndirectedRowsLine.createReversedLine(   "a6 b6 c6 d6 i6 j6 k6 l6" ),
            UndirectedRowsLine.createLine(           "a5 b5 c5 d5 i5 j5 k5 l5" ),
            UndirectedRowsLine.createReversedLine(   "a5 b5 c5 d5 i5 j5 k5 l5" ),

            UndirectedRowsLine.createLine(           "h12 g12 f12 e12 i12 j12 k12 l12" ),
            UndirectedRowsLine.createReversedLine(   "h12 g12 f12 e12 i12 j12 k12 l12" ),
            UndirectedRowsLine.createLine(           "h11 g11 f11 e11 i11 j11 k11 l11" ),
            UndirectedRowsLine.createReversedLine(   "h11 g11 f11 e11 i11 j11 k11 l11" ),
            UndirectedRowsLine.createLine(           "h10 g10 f10 e10 i10 j10 k10 l10" ),
            UndirectedRowsLine.createReversedLine(   "h10 g10 f10 e10 i10 j10 k10 l10" ),
            UndirectedRowsLine.createLine(           "h9 g9 f9 e9 i9 j9 k9 l9" ),
            UndirectedRowsLine.createReversedLine(   "h9 g9 f9 e9 i9 j9 k9 l9" ),

            DirectedFilesLine.createLine(          "a1 a2 a3 a4 a5 a6 a7 a8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createReversedLine(  "a1 a2 a3 a4 a5 a6 a7 a8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createLine(          "b1 b2 b3 b4 b5 b6 b7 b8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createReversedLine(  "b1 b2 b3 b4 b5 b6 b7 b8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createLine(          "c1 c2 c3 c4 c5 c6 c7 c8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createReversedLine(  "c1 c2 c3 c4 c5 c6 c7 c8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createLine(          "d1 d2 d3 d4 d5 d6 d7 d8", DIRECTED_WHITE_BLACK ),
            DirectedFilesLine.createReversedLine(  "d1 d2 d3 d4 d5 d6 d7 d8", DIRECTED_WHITE_BLACK ),

            DirectedFilesLine.createLine(          "e1 e2 e3 e4 e9 e10 e11 e12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createReversedLine(  "e1 e2 e3 e4 e9 e10 e11 e12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createLine(          "f1 f2 f3 f4 f9 f10 f11 f12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createReversedLine(  "f1 f2 f3 f4 f9 f10 f11 f12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createLine(          "g1 g2 g3 g4 g9 g10 g11 g12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createReversedLine(  "g1 g2 g3 g4 g9 g10 g11 g12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createLine(          "h1 h2 h3 h4 h9 h10 h11 h12", DIRECTED_WHITE_RED ),
            DirectedFilesLine.createReversedLine(  "h1 h2 h3 h4 h9 h10 h11 h12", DIRECTED_WHITE_RED ),

            DirectedFilesLine.createLine(          "i8 i7 i6 i5 i9 i10 i11 i12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createReversedLine(  "i8 i7 i6 i5 i9 i10 i11 i12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createLine(          "j8 j7 j6 j5 j9 j10 j11 j12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createReversedLine(  "j8 j7 j6 j5 j9 j10 j11 j12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createLine(          "k8 k7 k6 k5 k9 k10 k11 k12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createReversedLine(  "k8 k7 k6 k5 k9 k10 k11 k12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createLine(          "l8 l7 l6 l5 l9 l10 l11 l12", DIRECTED_BLACK_RED ),
            DirectedFilesLine.createReversedLine(  "l8 l7 l6 l5 l9 l10 l11 l12", DIRECTED_BLACK_RED ),

            DirectedDiagonalLine.createLine(         "a1 b2 c3 d4 i5 j6 k7 l8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a1 b2 c3 d4 i5 j6 k7 l8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "b1 a2", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "b1 a2", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "c1 b2 a3", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "c1 b2 a3", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "d1 c2 b3 a4", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "d1 c2 b3 a4", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "e1 d2 c3 b4 a5", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "e1 d2 c3 b4 a5", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "f1 e2 d3 c4 b5 a6", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "f1 e2 d3 c4 b5 a6", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "g1 f2 e3 d4 c5 b6 a7", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "g1 f2 e3 d4 c5 b6 a7", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "h1 g2 f3 e4 d5 c6 b7 a8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "h1 g2 f3 e4 d5 c6 b7 a8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "a2 b3 c4 d5 i6 j7 k8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a2 b3 c4 d5 i6 j7 k8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "a3 b4 c5 d6 i7 j8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a3 b4 c5 d6 i7 j8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "a4 b5 c6 d7 i8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a4 b5 c6 d7 i8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "a5 b6 c7 d8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a5 b6 c7 d8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createLine(         "a6 b7 c8" , DIRECTED_WHITE_BLACK),
            DirectedDiagonalLine.createReversedLine( "a6 b7 c8" , DIRECTED_WHITE_BLACK),
            DirectedDiagonalLine.createLine(         "a7 b8", DIRECTED_WHITE_BLACK ),
            DirectedDiagonalLine.createReversedLine( "a7 b8", DIRECTED_WHITE_BLACK ),

            DirectedDiagonalLine.createLine(         "h1 g2 f3 e4 i9 j10 k11 l12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h1 g2 f3 e4 i9 j10 k11 l12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h2 g3 f4 e9 i10 j11 k12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h2 g3 f4 e9 i10 j11 k12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h3 g4 f9 e10 i11 j12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h3 g4 f9 e10 i11 j12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h4 g9 f10 e11 i12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h4 g9 f10 e11 i12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h9 g10 f11 e12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h9 g10 f11 e12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h10 g11 f12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h10 g11 f12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "h11 g12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "h11 g12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "a1 b2 c3 d4 e9 f10 g11 h12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "a1 b2 c3 d4 e9 f10 g11 h12", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "b1 c2 d3 e4 f9 g10 h11", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "b1 c2 d3 e4 f9 g10 h11", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "c1 d2 e3 f4 g9 h10", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "c1 d2 e3 f4 g9 h10", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "d1 e2 f3 g4 h9", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "d1 e2 f3 g4 h9", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "e1 f2 g3 h4", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "e1 f2 g3 h4", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "f1 g2 h3", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "f1 g2 h3", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createLine(         "g1 h2", DIRECTED_WHITE_RED ),
            DirectedDiagonalLine.createReversedLine( "g1 h2", DIRECTED_WHITE_RED ),

            DirectedDiagonalLine.createLine(         "l8 k7 j6 i5 e9 f10 g11 h12", DIRECTED_BLACK_RED ),
            DirectedDiagonalLine.createReversedLine( "l8 k7 j6 i5 e9 f10 g11 h12", DIRECTED_BLACK_RED ),
            DirectedDiagonalLine.createLine(         "l7 k6 j5 i9 e10 f11 g12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l7 k6 j5 i9 e10 f11 g12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "l6 k5 j9 i10 e11 f12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l6 k5 j9 i10 e11 f12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "l5 k9 j10 i11 e12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l5 k9 j10 i11 e12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "l9 k10 j11 i12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l9 k10 j11 i12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "l10 k11 j12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l10 k11 j12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "l11 k12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "l11 k12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "a8 b7 c6 d5 i9 j10 k11 l12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "a8 b7 c6 d5 i9 j10 k11 l12", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "b8 c7 d6 i5 j9 k10 l11", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "b8 c7 d6 i5 j9 k10 l11", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "c8 d7 i6 j5 k9 l10", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "c8 d7 i6 j5 k9 l10", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "d8 i7 j6 k5 l9", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "d8 i7 j6 k5 l9", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "i8 j7 k6 l5", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "i8 j7 k6 l5", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "j8 k7 l6", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "j8 k7 l6", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createLine(         "k8 l7", DIRECTED_BLACK_RED  ),
            DirectedDiagonalLine.createReversedLine( "k8 l7", DIRECTED_BLACK_RED  ),

            KnightsLine.createLine(                       "a1 b3" ),
            KnightsLine.createReversedLine(               "a1 b3" ),
            KnightsLine.createLine(                       "a1 c2" ),
            KnightsLine.createReversedLine(               "a1 c2" ),
            KnightsLine.createLine(                       "b1 a3" ),
            KnightsLine.createReversedLine(               "b1 a3" ),
            KnightsLine.createLine(                       "b1 c3" ),
            KnightsLine.createReversedLine(               "b1 c3" ),
            KnightsLine.createReversedLine(               "b1 d2" ),
            KnightsLine.createLine(                       "b1 d2" ),
            KnightsLine.createReversedLine(               "c1 a2" ),
            KnightsLine.createLine(                       "c1 a2" ),
            KnightsLine.createReversedLine(               "c1 b3" ),
            KnightsLine.createLine(                       "c1 b3" ),
            KnightsLine.createReversedLine(               "c1 d3" ),
            KnightsLine.createLine(                       "c1 d3" ),
            KnightsLine.createLine(                       "c1 e2" ),
            KnightsLine.createReversedLine(               "c1 e2" ),
            KnightsLine.createLine(                       "d1 b2" ),
            KnightsLine.createReversedLine(               "d1 b2" ),
            KnightsLine.createLine(                       "d1 c3" ),
            KnightsLine.createReversedLine(               "d1 c3" ),
            KnightsLine.createLine(                       "d1 e3" ),
            KnightsLine.createReversedLine(               "d1 e3" ),
            KnightsLine.createReversedLine(               "d1 f2" ),
            KnightsLine.createLine(                       "d1 f2" ),
            KnightsLine.createReversedLine(               "e1 c2" ),
            KnightsLine.createLine(                       "e1 c2" ),
            KnightsLine.createReversedLine(               "e1 d3" ),
            KnightsLine.createLine(                       "e1 d3" ),
            KnightsLine.createReversedLine(               "e1 f3" ),
            KnightsLine.createLine(                       "e1 f3" ),
            KnightsLine.createLine(                       "e1 g2" ),
            KnightsLine.createReversedLine(               "e1 g2" ),
            KnightsLine.createLine(                       "f1 d2" ),
            KnightsLine.createReversedLine(               "f1 d2" ),
            KnightsLine.createLine(                       "f1 e3" ),
            KnightsLine.createReversedLine(               "f1 e3" ),
            KnightsLine.createReversedLine(               "f1 g3" ),
            KnightsLine.createLine(                       "f1 g3" ),
            KnightsLine.createReversedLine(               "f1 h2" ),
            KnightsLine.createLine(                       "f1 h2" ),
            KnightsLine.createReversedLine(               "g1 e2" ),
            KnightsLine.createLine(                       "g1 e2" ),
            KnightsLine.createReversedLine(               "g1 f3" ),
            KnightsLine.createLine(                       "g1 f3" ),
            KnightsLine.createReversedLine(               "g1 h3" ),
            KnightsLine.createLine(                       "g1 h3" ),
            KnightsLine.createLine(                       "h1 f2" ),
            KnightsLine.createReversedLine(               "h1 f2" ),
            KnightsLine.createLine(                       "h1 g3" ),
            KnightsLine.createReversedLine(               "h1 g3" ),

            KnightsLine.createLine(                       "a2 b4" ),
            KnightsLine.createReversedLine(               "a2 b4" ),
            KnightsLine.createLine(                       "a2 c3" ),
            KnightsLine.createReversedLine(               "a2 c3" ),
            KnightsLine.createLine(                       "b2 a4" ),
            KnightsLine.createReversedLine(               "b2 a4" ),
            KnightsLine.createLine(                       "b2 c4" ),
            KnightsLine.createReversedLine(               "b2 c4" ),
            KnightsLine.createLine(                       "b2 d3" ),
            KnightsLine.createReversedLine(               "b2 d3" ),
            KnightsLine.createLine(                       "c2 a3" ),
            KnightsLine.createReversedLine(               "c2 a3" ),
            KnightsLine.createLine(                       "c2 b4" ),
            KnightsLine.createReversedLine(               "c2 b4" ),
            KnightsLine.createLine(                       "c2 d4" ),
            KnightsLine.createReversedLine(               "c2 d4" ),
            KnightsLine.createLine(                       "c2 e3" ),
            KnightsLine.createReversedLine(               "c2 e3" ),
            KnightsLine.createLine(                       "d2 b3" ),
            KnightsLine.createReversedLine(               "d2 b3" ),
            KnightsLine.createLine(                       "d2 c4" ),
            KnightsLine.createReversedLine(               "d2 c4" ),
            KnightsLine.createLine(                       "d2 e4" ),
            KnightsLine.createReversedLine(               "d2 e4" ),
            KnightsLine.createLine(                       "d2 f3" ),
            KnightsLine.createReversedLine(               "d2 f3" ),
            KnightsLine.createLine(                       "e2 c3" ),
            KnightsLine.createReversedLine(               "e2 c3" ),
            KnightsLine.createLine(                       "e2 d4" ),
            KnightsLine.createReversedLine(               "e2 d4" ),
            KnightsLine.createLine(                       "e2 f4" ),
            KnightsLine.createReversedLine(               "e2 f4" ),
            KnightsLine.createLine(                       "e2 g3" ),
            KnightsLine.createReversedLine(               "e2 g3" ),
            KnightsLine.createLine(                       "f2 d3" ),
            KnightsLine.createReversedLine(               "f2 d3" ),
            KnightsLine.createLine(                       "f2 e4" ),
            KnightsLine.createReversedLine(               "f2 e4" ),
            KnightsLine.createLine(                       "f2 g4" ),
            KnightsLine.createReversedLine(               "f2 g4" ),
            KnightsLine.createLine(                       "f2 h3" ),
            KnightsLine.createReversedLine(               "f2 h3" ),
            KnightsLine.createLine(                       "g2 e3" ),
            KnightsLine.createReversedLine(               "g2 e3" ),
            KnightsLine.createLine(                       "g2 f4" ),
            KnightsLine.createReversedLine(               "g2 f4" ),
            KnightsLine.createLine(                       "g2 h4" ),
            KnightsLine.createReversedLine(               "g2 h4" ),
            KnightsLine.createLine(                       "h2 f3" ),
            KnightsLine.createReversedLine(               "h2 f3" ),
            KnightsLine.createLine(                       "h2 g4" ),
            KnightsLine.createReversedLine(               "h2 g4" ),

            KnightsLine.createLine(                       "a3 b5" ),
            KnightsLine.createReversedLine(               "a3 b5" ),
            KnightsLine.createLine(                       "a3 c4" ),
            KnightsLine.createReversedLine(               "a3 c4" ),
            KnightsLine.createLine(                       "b3 a5" ),
            KnightsLine.createReversedLine(               "b3 a5" ),
            KnightsLine.createLine(                       "b3 c5" ),
            KnightsLine.createReversedLine(               "b3 c5" ),
            KnightsLine.createLine(                       "b3 d4" ),
            KnightsLine.createReversedLine(               "b3 d4" ),
            KnightsLine.createLine(                       "c3 a4" ),
            KnightsLine.createReversedLine(               "c3 a4" ),
            KnightsLine.createLine(                       "c3 b5" ),
            KnightsLine.createReversedLine(               "c3 b5" ),
            KnightsLine.createLine(                       "c3 d5" ),
            KnightsLine.createReversedLine(               "c3 d5" ),
            KnightsLine.createLine(                       "c3 e4" ),
            KnightsLine.createReversedLine(               "c3 e4" ),
            KnightsLine.createLine(                       "d3 b4" ),
            KnightsLine.createReversedLine(               "d3 b4" ),
            KnightsLine.createLine(                       "d3 c5" ),
            KnightsLine.createReversedLine(               "d3 c5" ),
            KnightsLine.createLine(                       "d3 e9" ),
            KnightsLine.createReversedLine(               "d3 e9" ),
            KnightsLine.createLine(                       "d3 f4" ),
            KnightsLine.createReversedLine(               "d3 f4" ),
            KnightsLine.createLine(                       "e3 c4" ),
            KnightsLine.createReversedLine(               "e3 c4" ),
            KnightsLine.createLine(                       "e3 d5" ),
            KnightsLine.createReversedLine(               "e3 d5" ),
            KnightsLine.createLine(                       "e3 f9" ),
            KnightsLine.createReversedLine(               "e3 f9" ),
            KnightsLine.createLine(                       "e3 g4" ),
            KnightsLine.createReversedLine(               "e3 g4" ),
            KnightsLine.createLine(                       "f3 d4" ),
            KnightsLine.createReversedLine(               "f3 d4" ),
            KnightsLine.createLine(                       "f3 e9" ),
            KnightsLine.createReversedLine(               "f3 e9" ),
            KnightsLine.createLine(                       "f3 g9" ),
            KnightsLine.createReversedLine(               "f3 g9" ),
            KnightsLine.createLine(                       "f3 h4" ),
            KnightsLine.createReversedLine(               "f3 h4" ),
            KnightsLine.createLine(                       "g3 e4" ),
            KnightsLine.createReversedLine(               "g3 e4" ),
            KnightsLine.createLine(                       "g3 f9" ),
            KnightsLine.createReversedLine(               "g3 f9" ),
            KnightsLine.createLine(                       "g3 h9" ),
            KnightsLine.createReversedLine(               "g3 h9" ),
            KnightsLine.createLine(                       "h3 f4" ),
            KnightsLine.createReversedLine(               "h3 f4" ),
            KnightsLine.createLine(                       "h3 g9" ),
            KnightsLine.createReversedLine(               "h3 g9" ),

            KnightsLine.createLine(                       "a4 b6" ),
            KnightsLine.createReversedLine(               "a4 b6" ),
            KnightsLine.createLine(                       "a4 c5" ),
            KnightsLine.createReversedLine(               "a4 c5" ),
            KnightsLine.createLine(                       "b4 a6" ),
            KnightsLine.createReversedLine(               "b4 a6" ),
            KnightsLine.createLine(                       "b4 c6" ),
            KnightsLine.createReversedLine(               "b4 c6" ),
            KnightsLine.createLine(                       "b4 d5" ),
            KnightsLine.createReversedLine(               "b4 d5" ),
            KnightsLine.createLine(                       "c4 a5" ),
            KnightsLine.createReversedLine(               "c4 a5" ),
            KnightsLine.createLine(                       "c4 b6" ),
            KnightsLine.createReversedLine(               "c4 b6" ),
            KnightsLine.createLine(                       "c4 d6" ),
            KnightsLine.createReversedLine(               "c4 d6" ),
            KnightsLine.createLine(                       "c4 e9" ),
            KnightsLine.createReversedLine(               "c4 e9" ),
            KnightsLine.createLine(                       "c4 i5" ),
            KnightsLine.createReversedLine(               "c4 i5" ),
            KnightsLine.createLine(                       "d4 b5" ),
            KnightsLine.createReversedLine(               "d4 b5" ),
            KnightsLine.createLine(                       "d4 c6" ),
            KnightsLine.createReversedLine(               "d4 c6" ),
            KnightsLine.createLine(                       "d4 i6" ),
            KnightsLine.createReversedLine(               "d4 i6" ),
            KnightsLine.createLine(                       "d4 f9" ),
            KnightsLine.createReversedLine(               "d4 f9" ),
            KnightsLine.createLine(                       "e4 c5" ),
            KnightsLine.createReversedLine(               "e4 c5" ),
            KnightsLine.createLine(                       "e4 f10" ),
            KnightsLine.createReversedLine(               "e4 f10" ),
            KnightsLine.createLine(                       "e4 i10" ),
            KnightsLine.createReversedLine(               "e4 i10" ),
            KnightsLine.createLine(                       "e4 g9" ),
            KnightsLine.createReversedLine(               "e4 g9" ),
            KnightsLine.createLine(                       "f4 d5" ),
            KnightsLine.createReversedLine(               "f4 d5" ),
            KnightsLine.createLine(                       "f4 i9" ),
            KnightsLine.createReversedLine(               "f4 i9" ),
            KnightsLine.createLine(                       "f4 e10" ),
            KnightsLine.createReversedLine(               "f4 e10" ),
            KnightsLine.createLine(                       "f4 g10" ),
            KnightsLine.createReversedLine(               "f4 g10" ),
            KnightsLine.createLine(                       "f4 h9" ),
            KnightsLine.createReversedLine(               "f4 h9" ),
            KnightsLine.createLine(                       "g4 e9" ),
            KnightsLine.createReversedLine(               "g4 e9" ),
            KnightsLine.createLine(                       "g4 f10" ),
            KnightsLine.createReversedLine(               "g4 f10" ),
            KnightsLine.createLine(                       "g4 h10" ),
            KnightsLine.createReversedLine(               "g4 h10" ),
            KnightsLine.createLine(                       "h4 f9" ),
            KnightsLine.createReversedLine(               "h4 f9" ),
            KnightsLine.createLine(                       "h4 g10" ),
            KnightsLine.createReversedLine(               "h4 g10" ),

            KnightsLine.createLine(                       "h12 g10" ),
            KnightsLine.createReversedLine(               "h12 g10" ),
            KnightsLine.createLine(                       "h12 f11" ),
            KnightsLine.createReversedLine(               "h12 f11" ),
            KnightsLine.createLine(                       "g12 h10" ),
            KnightsLine.createReversedLine(               "g12 h10" ),
            KnightsLine.createLine(                       "g12 f10" ),
            KnightsLine.createReversedLine(               "g12 f10" ),
            KnightsLine.createLine(                       "g12 e11" ),
            KnightsLine.createReversedLine(               "g12 e11" ),
            KnightsLine.createLine(                       "f12 h11" ),
            KnightsLine.createReversedLine(               "f12 h11" ),
            KnightsLine.createLine(                       "f12 g10" ),
            KnightsLine.createReversedLine(               "f12 g10" ),
            KnightsLine.createLine(                       "f12 e10" ),
            KnightsLine.createReversedLine(               "f12 e10" ),
            KnightsLine.createLine(                       "f12 i11" ),
            KnightsLine.createReversedLine(               "f12 i11" ),
            KnightsLine.createLine(                       "e12 g11" ),
            KnightsLine.createReversedLine(               "e12 g11" ),
            KnightsLine.createLine(                       "e12 f10" ),
            KnightsLine.createReversedLine(               "e12 f10" ),
            KnightsLine.createLine(                       "e12 i10" ),
            KnightsLine.createReversedLine(               "e12 i10" ),
            KnightsLine.createLine(                       "e12 j11" ),
            KnightsLine.createReversedLine(               "e12 j11" ),
            KnightsLine.createLine(                       "i12 f11" ),
            KnightsLine.createReversedLine(               "i12 f11" ),
            KnightsLine.createLine(                       "i12 e10" ),
            KnightsLine.createReversedLine(               "i12 e10" ),
            KnightsLine.createLine(                       "i12 j10" ),
            KnightsLine.createReversedLine(               "i12 j10" ),
            KnightsLine.createLine(                       "i12 k11" ),
            KnightsLine.createReversedLine(               "i12 k11" ),
            KnightsLine.createLine(                       "j12 e11" ),
            KnightsLine.createReversedLine(               "j12 e11" ),
            KnightsLine.createLine(                       "j12 i10" ),
            KnightsLine.createReversedLine(               "j12 i10" ),
            KnightsLine.createLine(                       "j12 k10" ),
            KnightsLine.createReversedLine(               "j12 k10" ),
            KnightsLine.createLine(                       "j12 l11" ),
            KnightsLine.createReversedLine(               "j12 l11" ),
            KnightsLine.createLine(                       "k12 i11" ),
            KnightsLine.createReversedLine(               "k12 i11" ),
            KnightsLine.createLine(                       "k12 j10" ),
            KnightsLine.createReversedLine(               "k12 j10" ),
            KnightsLine.createLine(                       "k12 l10" ),
            KnightsLine.createReversedLine(               "k12 l10" ),
            KnightsLine.createLine(                       "l12 j11" ),
            KnightsLine.createReversedLine(               "l12 j11" ),
            KnightsLine.createLine(                       "l12 k10" ),
            KnightsLine.createReversedLine(               "l12 k10" ),

            KnightsLine.createLine(                       "h11 g9" ),
            KnightsLine.createReversedLine(               "h11 g9" ),
            KnightsLine.createLine(                       "h11 f10" ),
            KnightsLine.createReversedLine(               "h11 f10" ),
            KnightsLine.createLine(                       "g11 h9" ),
            KnightsLine.createReversedLine(               "g11 h9" ),
            KnightsLine.createLine(                       "g11 f9" ),
            KnightsLine.createReversedLine(               "g11 f9" ),
            KnightsLine.createLine(                        "g11 e10" ),
            KnightsLine.createReversedLine(               "g11 e10" ),
            KnightsLine.createLine(                       "f11 h10" ),
            KnightsLine.createReversedLine(               "f11 h10" ),
            KnightsLine.createLine(                       "f11 g9" ),
            KnightsLine.createReversedLine(               "f11 g9" ),
            KnightsLine.createLine(                       "f11 e9" ),
            KnightsLine.createReversedLine(               "f11 e9" ),
            KnightsLine.createLine(                       "f11 i10" ),
            KnightsLine.createReversedLine(               "f11 i10" ),
            KnightsLine.createLine(                       "e11 g10" ),
            KnightsLine.createReversedLine(               "e11 g10" ),
            KnightsLine.createLine(                       "e11 f9" ),
            KnightsLine.createReversedLine(               "e11 f9" ),
            KnightsLine.createLine(                       "e11 i9" ),
            KnightsLine.createReversedLine(               "e11 i9" ),
            KnightsLine.createLine(                       "e11 j10" ),
            KnightsLine.createReversedLine(               "e11 j10" ),
            KnightsLine.createLine(                       "i11 f10" ),
            KnightsLine.createReversedLine(               "i11 f10" ),
            KnightsLine.createLine(                       "i11 e9" ),
            KnightsLine.createReversedLine(               "i11 e9" ),
            KnightsLine.createLine(                       "i11 j9" ),
            KnightsLine.createReversedLine(               "i11 j9" ),
            KnightsLine.createLine(                       "i11 k10" ),
            KnightsLine.createReversedLine(               "i11 k10" ),
            KnightsLine.createLine(                       "j11 e10" ),
            KnightsLine.createReversedLine(               "j11 e10" ),
            KnightsLine.createLine(                       "j11 i9" ),
            KnightsLine.createReversedLine(               "j11 i9" ),
            KnightsLine.createLine(                       "j11 k9" ),
            KnightsLine.createReversedLine(               "j11 k9" ),
            KnightsLine.createLine(                       "j11 l10" ),
            KnightsLine.createReversedLine(               "j11 l10" ),
            KnightsLine.createLine(                       "k11 i10" ),
            KnightsLine.createReversedLine(               "k11 i10" ),
            KnightsLine.createLine(                       "k11 j9" ),
            KnightsLine.createReversedLine(               "k11 j9" ),
            KnightsLine.createLine(                       "k11 l9" ),
            KnightsLine.createReversedLine(               "k11 l9" ),
            KnightsLine.createLine(                       "l11 j10" ),
            KnightsLine.createReversedLine(               "l11 j10" ),
            KnightsLine.createLine(                       "l11 k9" ),
            KnightsLine.createReversedLine(               "l11 k9" ),

            KnightsLine.createLine(                       "h10 g4" ),
            KnightsLine.createReversedLine(               "h10 g4" ),
            KnightsLine.createLine(                       "h10 f9" ),
            KnightsLine.createReversedLine(               "h10 f9" ),
            KnightsLine.createLine(                       "g10 h4" ),
            KnightsLine.createReversedLine(               "g10 h4" ),
            KnightsLine.createLine(                       "g10 f4" ),
            KnightsLine.createReversedLine(               "g10 f4" ),
            KnightsLine.createLine(                       "g10 e9" ),
            KnightsLine.createReversedLine(               "g10 e9" ),
            KnightsLine.createLine(                       "f10 h9" ),
            KnightsLine.createReversedLine(               "f10 h9" ),
            KnightsLine.createLine(                       "f10 g4" ),
            KnightsLine.createReversedLine(               "f10 g4" ),
            KnightsLine.createLine(                       "f10 e4" ),
            KnightsLine.createReversedLine(               "f10 e4" ),
            KnightsLine.createLine(                       "f10 i9" ),
            KnightsLine.createReversedLine(               "f10 i9" ),
            KnightsLine.createLine(                       "f10 i11" ),
            KnightsLine.createReversedLine(               "f10 i11" ),
            KnightsLine.createLine(                       "e10 g9" ),
            KnightsLine.createReversedLine(               "e10 g9" ),
            KnightsLine.createLine(                       "e10 f4" ),
            KnightsLine.createReversedLine(               "e10 f4" ),
            KnightsLine.createLine(                       "e10 d4" ),
            KnightsLine.createReversedLine(               "e10 d4" ),
            KnightsLine.createLine(                       "e10 i5" ),
            KnightsLine.createReversedLine(               "e10 i5" ),
            KnightsLine.createLine(                       "e10 j9" ),
            KnightsLine.createReversedLine(               "e10 j9" ),
            KnightsLine.createLine(                       "i10 f9" ),
            KnightsLine.createReversedLine(               "i10 f9" ),
            KnightsLine.createLine(                       "i10 e4" ),
            KnightsLine.createReversedLine(               "i10 e4" ),
            KnightsLine.createLine(                       "i10 j5" ),
            KnightsLine.createReversedLine(               "i10 j5" ),
            KnightsLine.createLine(                       "i10 k9" ),
            KnightsLine.createReversedLine(               "i10 k9" ),
            KnightsLine.createLine(                       "j10 e9" ),
            KnightsLine.createReversedLine(               "j10 e9" ),
            KnightsLine.createLine(                       "j10 i5" ),
            KnightsLine.createReversedLine(               "j10 i5" ),
            KnightsLine.createLine(                       "j10 k5" ),
            KnightsLine.createReversedLine(               "j10 k5" ),
            KnightsLine.createLine(                       "j10 l9" ),
            KnightsLine.createReversedLine(               "j10 l9" ),
            KnightsLine.createLine(                       "k10 i9" ),
            KnightsLine.createReversedLine(               "k10 i9" ),
            KnightsLine.createLine(                       "k10 j5" ),
            KnightsLine.createReversedLine(               "k10 j5" ),
            KnightsLine.createLine(                       "k10 l5" ),
            KnightsLine.createReversedLine(               "k10 l5" ),
            KnightsLine.createLine(                       "l10 j9" ),
            KnightsLine.createReversedLine(               "l10 j9" ),
            KnightsLine.createLine(                       "l10 k5" ),
            KnightsLine.createReversedLine(               "l10 k5" ),

            KnightsLine.createLine(                       "h9 g3" ),
            KnightsLine.createReversedLine(               "h9 g3" ),
            KnightsLine.createLine(                       "h9 f4" ),
            KnightsLine.createReversedLine(               "h9 f4" ),
            KnightsLine.createLine(                       "g9 h3" ),
            KnightsLine.createReversedLine(               "g9 h3" ),
            KnightsLine.createLine(                       "g9 f3" ),
            KnightsLine.createReversedLine(               "g9 f3" ),
            KnightsLine.createLine(                       "g9 e4" ),
            KnightsLine.createReversedLine(               "g9 e4" ),
            KnightsLine.createLine(                       "f9 h4" ),
            KnightsLine.createReversedLine(               "f9 h4" ),
            KnightsLine.createLine(                       "f9 g3" ),
            KnightsLine.createReversedLine(               "f9 g3" ),
            KnightsLine.createLine(                       "f9 e3" ),
            KnightsLine.createReversedLine(               "f9 e3" ),
            KnightsLine.createLine(                       "f9 d4" ),
            KnightsLine.createReversedLine(               "f9 d4" ),
            KnightsLine.createLine(                       "f9 i5" ),
            KnightsLine.createReversedLine(               "f9 i5" ),
            KnightsLine.createLine(                       "e9 g4" ),
            KnightsLine.createReversedLine(               "e9 g4" ),
            KnightsLine.createLine(                       "e9 f3" ),
            KnightsLine.createReversedLine(               "e9 f3" ),
            KnightsLine.createLine(                       "e9 d3" ),
            KnightsLine.createReversedLine(               "e9 d3" ),
            KnightsLine.createLine(                       "e9 j5" ),
            KnightsLine.createReversedLine(               "e9 j5" ),
            KnightsLine.createLine(                       "i9 f4" ),
            KnightsLine.createReversedLine(               "i9 f4" ),
            KnightsLine.createLine(                       "i9 d6" ),
            KnightsLine.createReversedLine(               "i9 d6" ),
            KnightsLine.createLine(                       "i9 j6" ),
            KnightsLine.createReversedLine(               "i9 j6" ),
            KnightsLine.createLine(                       "i9 k5" ),
            KnightsLine.createReversedLine(               "i9 k5" ),
            KnightsLine.createLine(                       "j9 d5" ),
            KnightsLine.createReversedLine(               "j9 d5" ),
            KnightsLine.createLine(                       "j9 e4" ),
            KnightsLine.createReversedLine(               "j9 e4" ),
            KnightsLine.createLine(                       "j9 i6" ),
            KnightsLine.createReversedLine(               "j9 i6" ),
            KnightsLine.createLine(                       "j9 k6" ),
            KnightsLine.createReversedLine(               "j9 k6" ),
            KnightsLine.createLine(                       "j9 l5" ),
            KnightsLine.createReversedLine(               "j9 l5" ),
            KnightsLine.createLine(                       "k9 i5" ),
            KnightsLine.createReversedLine(               "k9 i5" ),
            KnightsLine.createLine(                       "k9 j6" ),
            KnightsLine.createReversedLine(               "k9 j6" ),
            KnightsLine.createLine(                       "k9 l6" ),
            KnightsLine.createReversedLine(               "k9 l6" ),
            KnightsLine.createLine(                       "l9 j5" ),
            KnightsLine.createReversedLine(               "l9 j5" ),
            KnightsLine.createLine(                       "l9 k6" ),
            KnightsLine.createReversedLine(               "l9 k6" ),

            KnightsLine.createLine(                       "l8 k6" ),
            KnightsLine.createReversedLine(               "l8 k6" ),
            KnightsLine.createLine(                       "l8 j7" ),
            KnightsLine.createReversedLine(               "l8 j7" ),
            KnightsLine.createLine(                       "k8 l6" ),
            KnightsLine.createReversedLine(               "k8 l6" ),
            KnightsLine.createLine(                       "k8 j6" ),
            KnightsLine.createReversedLine(               "k8 j6" ),
            KnightsLine.createLine(                       "k8 i7" ),
            KnightsLine.createReversedLine(               "k8 i7" ),
            KnightsLine.createLine(                       "j8 l7" ),
            KnightsLine.createReversedLine(               "j8 l7" ),
            KnightsLine.createLine(                       "j8 k6" ),
            KnightsLine.createReversedLine(               "j8 k6" ),
            KnightsLine.createLine(                       "j8 i6" ),
            KnightsLine.createReversedLine(               "j8 i6" ),
            KnightsLine.createLine(                       "j8 d7" ),
            KnightsLine.createReversedLine(               "j8 d7" ),
            KnightsLine.createLine(                       "i8 k7" ),
            KnightsLine.createReversedLine(               "i8 k7" ),
            KnightsLine.createLine(                       "i8 j6" ),
            KnightsLine.createReversedLine(               "i8 j6" ),
            KnightsLine.createLine(                       "i8 d6" ),
            KnightsLine.createReversedLine(               "i8 d6" ),
            KnightsLine.createLine(                       "i8 c7" ),
            KnightsLine.createReversedLine(               "i8 c7" ),
            KnightsLine.createLine(                       "d8 j7" ),
            KnightsLine.createReversedLine(               "d8 j7" ),
            KnightsLine.createLine(                       "d8 i6" ),
            KnightsLine.createReversedLine(               "d8 i6" ),
            KnightsLine.createLine(                       "d8 c6" ),
            KnightsLine.createReversedLine(               "d8 c6" ),
            KnightsLine.createLine(                       "d8 b7" ),
            KnightsLine.createReversedLine(               "d8 b7" ),
            KnightsLine.createLine(                       "c8 i7" ),
            KnightsLine.createReversedLine(               "c8 i7" ),
            KnightsLine.createLine(                       "c8 d6" ),
            KnightsLine.createReversedLine(               "c8 d6" ),
            KnightsLine.createLine(                       "c8 b6" ),
            KnightsLine.createReversedLine(               "c8 b6" ),
            KnightsLine.createLine(                       "c8 a7" ),
            KnightsLine.createReversedLine(               "c8 a7" ),
            KnightsLine.createLine(                       "b8 d7" ),
            KnightsLine.createReversedLine(               "b8 d7" ),
            KnightsLine.createLine(                       "b8 c6" ),
            KnightsLine.createReversedLine(               "b8 c6" ),
            KnightsLine.createLine(                       "b8 a6" ),
            KnightsLine.createReversedLine(               "b8 a6" ),
            KnightsLine.createLine(                       "a8 c7" ),
            KnightsLine.createReversedLine(               "a8 c7" ),
            KnightsLine.createLine(                       "a8 b6" ),
            KnightsLine.createReversedLine(               "a8 b6" ),

            KnightsLine.createLine(                       "l7 k5" ),
            KnightsLine.createReversedLine(               "l7 k5" ),
            KnightsLine.createLine(                       "l7 j6" ),
            KnightsLine.createReversedLine(               "l7 j6" ),
            KnightsLine.createLine(                       "k7 l5" ),
            KnightsLine.createReversedLine(               "k7 l5" ),
            KnightsLine.createLine(                       "k7 j5" ),
            KnightsLine.createReversedLine(               "k7 j5" ),
            KnightsLine.createLine(                       "k7 i6" ),
            KnightsLine.createReversedLine(               "k7 i6" ),
            KnightsLine.createLine(                       "j7 l6" ),
            KnightsLine.createReversedLine(               "j7 l6" ),
            KnightsLine.createLine(                       "j7 k5" ),
            KnightsLine.createReversedLine(               "j7 k5" ),
            KnightsLine.createLine(                       "j7 i5" ),
            KnightsLine.createReversedLine(               "j7 i5" ),
            KnightsLine.createLine(                       "j7 d6" ),
            KnightsLine.createReversedLine(               "j7 d6" ),
            KnightsLine.createLine(                       "i7 k6" ),
            KnightsLine.createReversedLine(               "i7 k6" ),
            KnightsLine.createLine(                       "i7 j5" ),
            KnightsLine.createReversedLine(               "i7 j5" ),
            KnightsLine.createLine(                       "i7 d5" ),
            KnightsLine.createReversedLine(               "i7 d5" ),
            KnightsLine.createLine(                       "i7 c6" ),
            KnightsLine.createReversedLine(               "i7 c6" ),
            KnightsLine.createLine(                       "d7 j6" ),
            KnightsLine.createReversedLine(               "d7 j6" ),
            KnightsLine.createLine(                       "d7 i5" ),
            KnightsLine.createReversedLine(               "d7 i5" ),
            KnightsLine.createLine(                       "d7 c5" ),
            KnightsLine.createReversedLine(               "d7 c5" ),
            KnightsLine.createLine(                       "d7 b6" ),
            KnightsLine.createReversedLine(               "d7 b6" ),
            KnightsLine.createLine(                       "c7 i6" ),
            KnightsLine.createReversedLine(               "c7 i6" ),
            KnightsLine.createLine(                       "c7 d5" ),
            KnightsLine.createReversedLine(               "c7 d5" ),
            KnightsLine.createLine(                       "c7 b5" ),
            KnightsLine.createReversedLine(               "c7 b5" ),
            KnightsLine.createLine(                       "c7 a6" ),
            KnightsLine.createReversedLine(               "c7 a6" ),
            KnightsLine.createLine(                       "b7 d6" ),
            KnightsLine.createReversedLine(               "b7 d6" ),
            KnightsLine.createLine(                       "b7 c5" ),
            KnightsLine.createReversedLine(               "b7 c5" ),
            KnightsLine.createLine(                       "b7 a5" ),
            KnightsLine.createReversedLine(               "b7 a5" ),
            KnightsLine.createLine(                       "a7 c6" ),
            KnightsLine.createReversedLine(               "a7 c6" ),
            KnightsLine.createLine(                       "a7 b5" ),
            KnightsLine.createReversedLine(               "a7 b5" ),

            KnightsLine.createLine(                       "l6 k9" ),
            KnightsLine.createReversedLine(               "l6 k9" ),
            KnightsLine.createLine(                       "l6 j5" ),
            KnightsLine.createReversedLine(               "l6 j5" ),
            KnightsLine.createLine(                       "k6 l9" ),
            KnightsLine.createReversedLine(               "k6 l9" ),
            KnightsLine.createLine(                       "k6 j9" ),
            KnightsLine.createReversedLine(               "k6 j9" ),
            KnightsLine.createLine(                       "k6 i5" ),
            KnightsLine.createReversedLine(               "k6 i5" ),
            KnightsLine.createLine(                       "j6 l5" ),
            KnightsLine.createReversedLine(               "j6 l5" ),
            KnightsLine.createLine(                       "j6 k9" ),
            KnightsLine.createReversedLine(               "j6 k9" ),
            KnightsLine.createLine(                       "j6 i9" ),
            KnightsLine.createReversedLine(               "j6 i9" ),
            KnightsLine.createLine(                       "j6 d5" ),
            KnightsLine.createReversedLine(               "j6 d5" ),
            KnightsLine.createLine(                       "i6 k5" ),
            KnightsLine.createReversedLine(               "i6 k5" ),
            KnightsLine.createLine(                       "i6 j9" ),
            KnightsLine.createReversedLine(               "i6 j9" ),
            KnightsLine.createLine(                       "i6 e9" ),
            KnightsLine.createReversedLine(               "i6 e9" ),
            KnightsLine.createLine(                       "i6 d4" ),
            KnightsLine.createReversedLine(               "i6 d4" ),
            KnightsLine.createLine(                       "i6 c5" ),
            KnightsLine.createReversedLine(               "i6 c5" ),
            KnightsLine.createLine(                       "d6 j5" ),
            KnightsLine.createReversedLine(               "d6 j5" ),
            KnightsLine.createLine(                       "d6 i9" ),
            KnightsLine.createReversedLine(               "d6 i9" ),
            KnightsLine.createLine(                       "d6 e4" ),
            KnightsLine.createReversedLine(               "d6 e4" ),
            KnightsLine.createLine(                       "d6 c4" ),
            KnightsLine.createReversedLine(               "d6 c4" ),
            KnightsLine.createLine(                       "d6 b5" ),
            KnightsLine.createReversedLine(               "d6 b5" ),
            KnightsLine.createLine(                       "c6 i5" ),
            KnightsLine.createReversedLine(               "c6 i5" ),
            KnightsLine.createLine(                       "c6 d4" ),
            KnightsLine.createReversedLine(               "c6 d4" ),
            KnightsLine.createLine(                       "c6 b4" ),
            KnightsLine.createReversedLine(               "c6 b4" ),
            KnightsLine.createLine(                       "c6 a5" ),
            KnightsLine.createReversedLine(               "c6 a5" ),
            KnightsLine.createLine(                       "b6 d5" ),
            KnightsLine.createReversedLine(               "b6 d5" ),
            KnightsLine.createLine(                       "b6 c4" ),
            KnightsLine.createReversedLine(               "b6 c4" ),
            KnightsLine.createLine(                       "b6 a4" ),
            KnightsLine.createReversedLine(               "b6 a4" ),
            KnightsLine.createLine(                       "a6 c5" ),
            KnightsLine.createReversedLine(               "a6 c5" ),
            KnightsLine.createLine(                       "a6 b4" ),
            KnightsLine.createReversedLine(               "a6 b4" ),

            KnightsLine.createLine(                       "l5 k10" ),
            KnightsLine.createReversedLine(               "l5 k10" ),
            KnightsLine.createLine(                       "l5 j9" ),
            KnightsLine.createReversedLine(               "l5 j9" ),
            KnightsLine.createLine(                       "k5 l10" ),
            KnightsLine.createReversedLine(               "k5 l10" ),
            KnightsLine.createLine(                       "k5 j10" ),
            KnightsLine.createReversedLine(               "k5 j10" ),
            KnightsLine.createLine(                       "k5 i9" ),
            KnightsLine.createReversedLine(               "k5 i9" ),
            KnightsLine.createLine(                       "j5 l9" ),
            KnightsLine.createReversedLine(               "j5 l9" ),
            KnightsLine.createLine(                       "j5 k10" ),
            KnightsLine.createReversedLine(               "j5 k10" ),
            KnightsLine.createLine(                       "j5 i10" ),
            KnightsLine.createReversedLine(               "j5 i10" ),
            KnightsLine.createLine(                       "j5 e9" ),
            KnightsLine.createReversedLine(               "j5 e9" ),
            KnightsLine.createLine(                       "j5 d4" ),
            KnightsLine.createReversedLine(               "j5 d4" ),
            KnightsLine.createLine(                       "i5 k9" ),
            KnightsLine.createReversedLine(               "i5 k9" ),
            KnightsLine.createLine(                       "i5 j10" ),
            KnightsLine.createReversedLine(               "i5 j10" ),
            KnightsLine.createLine(                       "i5 e10" ),
            KnightsLine.createReversedLine(               "i5 e10" ),
            KnightsLine.createLine(                       "i5 c4" ),
            KnightsLine.createReversedLine(               "i5 c4" ),
            KnightsLine.createLine(                       "d5 j9" ),
            KnightsLine.createReversedLine(               "d5 j9" ),
            KnightsLine.createLine(                       "d5 e3" ),
            KnightsLine.createReversedLine(               "d5 e3" ),
            KnightsLine.createLine(                       "d5 c3" ),
            KnightsLine.createReversedLine(               "d5 c3" ),
            KnightsLine.createLine(                       "d5 b4" ),
            KnightsLine.createReversedLine(               "d5 b4" ),
            KnightsLine.createLine(                       "c5 i9" ),
            KnightsLine.createReversedLine(               "c5 i9" ),
            KnightsLine.createLine(                       "c5 e4" ),
            KnightsLine.createReversedLine(               "c5 e4" ),
            KnightsLine.createLine(                       "c5 d3" ),
            KnightsLine.createReversedLine(               "c5 d3" ),
            KnightsLine.createLine(                       "c5 b3" ),
            KnightsLine.createReversedLine(               "c5 b3" ),
            KnightsLine.createLine(                       "c5 a4" ),
            KnightsLine.createReversedLine(               "c5 a4" ),
            KnightsLine.createLine(                       "b5 d4" ),
            KnightsLine.createReversedLine(               "b5 d4" ),
            KnightsLine.createLine(                       "b5 c3" ),
            KnightsLine.createReversedLine(               "b5 c3" ),
            KnightsLine.createLine(                       "b5 a3" ),
            KnightsLine.createReversedLine(               "b5 a3" ),
            KnightsLine.createLine(                       "a5 c4" ),
            KnightsLine.createReversedLine(               "a5 c4" ),
            KnightsLine.createLine(                       "a5 b3" ),
            KnightsLine.createReversedLine(               "a5 b3" )

    );
}


