/*
 *  TripleBoardByRectangles.java
 *
 *  chess383 is a collection of chess related utilities.
 *  Copyright (C) 2015 - 2021 Jörg Dippel
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package chess383.graph.board;

import java.util.List;

import chess383.ColorEnum;
import chess383.ICoordinate;
import chess383.graph.direction.Direction;
import chess383.graph.line.LineOfLocations;

/**
 * Provides locations on a bundle of lines for a board for three players: rectangles within a hexagon.
 *
 * @author    Jörg Dippel
 * @version   February 2021
 *
 */
public class TripleBoardByRectangles extends LineBundle {
    
    private final static Direction DIRECTED_WHITE_BLACK = Direction.createUnidirectionalDirection( ColorEnum.WHITE, ColorEnum.BLACK );
    private final static Direction DIRECTED_WHITE_RED =   Direction.createUnidirectionalDirection( ColorEnum.WHITE, ColorEnum.RED );
    private final static Direction DIRECTED_BLACK_RED =   Direction.createUnidirectionalDirection( ColorEnum.BLACK, ColorEnum.RED );
    
    static private TripleBoardByRectangles singleton = new TripleBoardByRectangles();
    static public ICoordinate getInstance() { return singleton; }
    static public List<LineOfLocations> getStaticBundle() { return TripleBoardByRectangles.bundle; }
    
    public List<LineOfLocations> getBundle() { return getStaticBundle(); }
       
    private TripleBoardByRectangles( ) {}

    /** ------------------------------------------------------- */
    
    //  final int NUMBER_OF_LINES = 407;
    static private List<LineOfLocations> bundle = List.of( 

        // createFileLine( VERTICAL, value )
        
        createRankLine( "a1 b1 c1 d1 e1 f1 g1 h1" ),
        createRankLine( "a2 b2 c2 d2 e2 f2 g2 h2" ),
        createRankLine( "a3 b3 c3 d3 e3 f3 g3 h3" ),
        createRankLine( "a4 b4 c4 d4 e4 f4 g4 h4" ),
        
        createRankLine( "a8 b8 c8 d8 i8 j8 k8 l8" ),
        createRankLine( "a7 b7 c7 d7 i7 j7 k7 l7" ),
        createRankLine( "a6 b6 c6 d6 i6 j6 k6 l6" ),
        createRankLine( "a5 b5 c5 d5 i5 j5 k5 l5" ),
        
        createRankLine( "h12 g12 f12 e12 i12 j12 k12 l12" ),
        createRankLine( "h11 g11 f11 e11 i11 j11 k11 l11" ),
        createRankLine( "h10 g10 f10 e10 i10 j10 k10 l10" ),
        createRankLine( "h9 g9 f9 e9 i9 j9 k9 l9" ),
        
        createFileLine( "a1 a2 a3 a4 a5 a6 a7 a8", DIRECTED_WHITE_BLACK ),
        createFileLine( "b1 b2 b3 b4 b5 b6 b7 b8", DIRECTED_WHITE_BLACK ),
        createFileLine( "c1 c2 c3 c4 c5 c6 c7 c8", DIRECTED_WHITE_BLACK ),
        createFileLine( "d1 d2 d3 d4 d5 d6 d7 d8", DIRECTED_WHITE_BLACK ),
        
        createFileLine( "e1 e2 e3 e4 e9 e10 e11 e12", DIRECTED_WHITE_RED ),
        createFileLine( "f1 f2 f3 f4 f9 f10 f11 f12", DIRECTED_WHITE_RED ),
        createFileLine( "g1 g2 g3 g4 g9 g10 g11 g12", DIRECTED_WHITE_RED ),
        createFileLine( "h1 h2 h3 h4 h9 h10 h11 h12", DIRECTED_WHITE_RED ),
        
        createFileLine( "i8 i7 i6 i5 i9 i10 i11 i12", DIRECTED_BLACK_RED ),
        createFileLine( "j8 j7 j6 j5 j9 j10 j11 j12", DIRECTED_BLACK_RED ),
        createFileLine( "k8 k7 k6 k5 k9 k10 k11 k12", DIRECTED_BLACK_RED ),
        createFileLine( "l8 l7 l6 l5 l9 l10 l11 l12", DIRECTED_BLACK_RED ),
        
        createDiagonalLine( "a1 b2 c3 d4 i5 j6 k7 l8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "b1 a2", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "c1 b2 a3", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "d1 c2 b3 a4", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "e1 d2 c3 b4 a5", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "f1 e2 d3 c4 b5 a6", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "g1 f2 e3 d4 c5 b6 a7", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "h1 g2 f3 e4 d5 c6 b7 a8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "a2 b3 c4 d5 i6 j7 k8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "a3 b4 c5 d6 i7 j8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "a4 b5 c6 d7 i8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "a5 b6 c7 d8", DIRECTED_WHITE_BLACK ),
        createDiagonalLine( "a6 b7 c8" , DIRECTED_WHITE_BLACK),
        createDiagonalLine( "a7 b8", DIRECTED_WHITE_BLACK ),
        
        createDiagonalLine( "h1 g2 f3 e4 i9 j10 k11 l12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h2 g3 f4 e9 i10 j11 k12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h3 g4 f9 e10 i11 j12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h4 g9 f10 e11 i12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h9 g10 f11 e12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h10 g11 f12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "h11 g12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "a1 b2 c3 d4 e9 f10 g11 h12", DIRECTED_WHITE_RED ),
        createDiagonalLine( "b1 c2 d3 e4 f9 g10 h11", DIRECTED_WHITE_RED ),
        createDiagonalLine( "c1 d2 e3 f4 g9 h10", DIRECTED_WHITE_RED ),
        createDiagonalLine( "d1 e2 f3 g4 h9", DIRECTED_WHITE_RED ),
        createDiagonalLine( "e1 f2 g3 h4", DIRECTED_WHITE_RED ),
        createDiagonalLine( "f1 g2 h3", DIRECTED_WHITE_RED ),
        createDiagonalLine( "g1 h2", DIRECTED_WHITE_RED ),

        createDiagonalLine( "l8 k7 j6 i5 e9 f10 g11 h12", DIRECTED_BLACK_RED ),
        createDiagonalLine( "l7 k6 j5 i9 e10 f11 g12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "l6 k5 j9 i10 e11 f12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "l5 k9 j10 i11 e12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "l9 k10 j11 i12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "l10 k11 j12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "l11 k12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "a8 b7 c6 d5 i9 j10 k11 l12", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "b8 c7 d6 i5 j9 k10 l11", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "c8 d7 i6 j5 k9 l10", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "d8 i7 j6 k5 l9", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "i8 j7 k6 l5", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "j8 k7 l6", DIRECTED_BLACK_RED  ),
        createDiagonalLine( "k8 l7", DIRECTED_BLACK_RED  ),
        
        createKnightLine( "a1 b3" ),
        createKnightLine( "a1 c2" ),
        createKnightLine( "b1 a3" ),        
        createKnightLine( "b1 c3" ),
        createKnightLine( "b1 d2" ),
        createKnightLine( "c1 a2" ),
        createKnightLine( "c1 b3" ),        
        createKnightLine( "c1 d3" ),
        createKnightLine( "c1 e2" ),
        createKnightLine( "d1 b2" ),
        createKnightLine( "d1 c3" ),        
        createKnightLine( "d1 e3" ),
        createKnightLine( "d1 f2" ),
        createKnightLine( "e1 c2" ),
        createKnightLine( "e1 d3" ),        
        createKnightLine( "e1 f3" ),
        createKnightLine( "e1 g2" ),
        createKnightLine( "f1 d2" ),
        createKnightLine( "f1 e3" ),        
        createKnightLine( "f1 g3" ),
        createKnightLine( "f1 h2" ),
        createKnightLine( "g1 e2" ),
        createKnightLine( "g1 f3" ),        
        createKnightLine( "g1 h3" ),
        createKnightLine( "h1 f2" ),        
        createKnightLine( "h1 g3" ),
        
        createKnightLine( "a2 b4" ),
        createKnightLine( "a2 c3" ),
        createKnightLine( "b2 a4" ),
        createKnightLine( "b2 c4" ),
        createKnightLine( "b2 d3" ),
        createKnightLine( "c2 a3" ),
        createKnightLine( "c2 b4" ),
        createKnightLine( "c2 d4" ),
        createKnightLine( "c2 e3" ),
        createKnightLine( "d2 b3" ),
        createKnightLine( "d2 c4" ),
        createKnightLine( "d2 e4" ),
        createKnightLine( "d2 f3" ),
        createKnightLine( "e2 c3" ),
        createKnightLine( "e2 d4" ),
        createKnightLine( "e2 f4" ),
        createKnightLine( "e2 g3" ),
        createKnightLine( "f2 d3" ),
        createKnightLine( "f2 e4" ),
        createKnightLine( "f2 g4" ),
        createKnightLine( "f2 h3" ),
        createKnightLine( "g2 e3" ),
        createKnightLine( "g2 f4" ),
        createKnightLine( "g2 h4" ),
        createKnightLine( "h2 f3" ),
        createKnightLine( "h2 g4" ),
        
        createKnightLine( "a3 b5" ),
        createKnightLine( "a3 c4" ),
        createKnightLine( "b3 a5" ),
        createKnightLine( "b3 c5" ),
        createKnightLine( "b3 d4" ),
        createKnightLine( "c3 a4" ),
        createKnightLine( "c3 b5" ),
        createKnightLine( "c3 d5" ),
        createKnightLine( "c3 e4" ),
        createKnightLine( "d3 b4" ),
        createKnightLine( "d3 c5" ),
        createKnightLine( "d3 e9" ),
        createKnightLine( "d3 f4" ),
        createKnightLine( "e3 c4" ),
        createKnightLine( "e3 d5" ),
        createKnightLine( "e3 f9" ),
        createKnightLine( "e3 g4" ),
        createKnightLine( "f3 d4" ),
        createKnightLine( "f3 e9" ),
        createKnightLine( "f3 g9" ),
        createKnightLine( "f3 h4" ),
        createKnightLine( "g3 e4" ),
        createKnightLine( "g3 f9" ),
        createKnightLine( "g3 h9" ),
        createKnightLine( "h3 f4" ),
        createKnightLine( "h3 g9" ),        
        
        createKnightLine( "a4 b6" ),
        createKnightLine( "a4 c5" ),
        createKnightLine( "b4 a6" ),
        createKnightLine( "b4 c6" ),
        createKnightLine( "b4 d5" ),
        createKnightLine( "c4 a5" ),
        createKnightLine( "c4 b6" ),
        createKnightLine( "c4 d6" ),
        createKnightLine( "c4 e9" ),
        createKnightLine( "c4 i5" ),
        createKnightLine( "d4 b5" ),
        createKnightLine( "d4 c6" ),
        createKnightLine( "d4 i6" ),
        createKnightLine( "d4 f9" ),
        createKnightLine( "e4 c5" ),
        createKnightLine( "e4 f10" ),
        createKnightLine( "e4 i10" ),
        createKnightLine( "e4 g9" ),
        createKnightLine( "f4 d5" ),
        createKnightLine( "f4 i9" ),
        createKnightLine( "f4 e10" ),
        createKnightLine( "f4 g10" ),
        createKnightLine( "f4 h9" ),
        createKnightLine( "g4 e9" ),
        createKnightLine( "g4 f10" ),
        createKnightLine( "g4 h10" ),
        createKnightLine( "h4 f9" ),
        createKnightLine( "h4 g10" ),
        
        createKnightLine( "h12 g10" ),
        createKnightLine( "h12 f11" ),
        createKnightLine( "g12 h10" ),
        createKnightLine( "g12 f10" ),
        createKnightLine( "g12 e11" ),
        createKnightLine( "f12 h11" ),
        createKnightLine( "f12 g10" ),
        createKnightLine( "f12 e10" ),
        createKnightLine( "f12 i11" ),
        createKnightLine( "e12 g11" ),
        createKnightLine( "e12 f10" ),
        createKnightLine( "e12 i10" ),
        createKnightLine( "e12 j11" ),
        createKnightLine( "i12 f11" ),
        createKnightLine( "i12 e10" ),
        createKnightLine( "i12 j10" ),
        createKnightLine( "i12 k11" ),
        createKnightLine( "j12 e11" ),
        createKnightLine( "j12 i10" ),
        createKnightLine( "j12 k10" ),
        createKnightLine( "j12 l11" ),
        createKnightLine( "k12 i11" ),
        createKnightLine( "k12 j10" ),
        createKnightLine( "k12 l10" ),
        createKnightLine( "l12 j11" ),
        createKnightLine( "l12 k10" ),
        
        createKnightLine( "h11 g9" ),
        createKnightLine( "h11 f10" ),
        createKnightLine( "g11 h9" ),
        createKnightLine( "g11 f9" ),
        createKnightLine( "g11 e10" ),
        createKnightLine( "f11 h10" ),
        createKnightLine( "f11 g9" ),
        createKnightLine( "f11 e9" ),
        createKnightLine( "f11 i10" ),
        createKnightLine( "e11 g10" ),
        createKnightLine( "e11 f9" ),
        createKnightLine( "e11 i9" ),
        createKnightLine( "e11 j10" ),
        createKnightLine( "i11 f10" ),
        createKnightLine( "i11 e9" ),
        createKnightLine( "i11 j9" ),
        createKnightLine( "i11 k10" ),
        createKnightLine( "j11 e10" ),
        createKnightLine( "j11 i9" ),
        createKnightLine( "j11 k9" ),
        createKnightLine( "j11 l10" ),
        createKnightLine( "k11 i10" ),
        createKnightLine( "k11 j9" ),
        createKnightLine( "k11 l9" ),
        createKnightLine( "l11 j10" ),
        createKnightLine( "l11 k9" ),
        
        createKnightLine( "h10 g4" ),
        createKnightLine( "h10 f9" ),
        createKnightLine( "g10 h4" ),
        createKnightLine( "g10 f4" ),
        createKnightLine( "g10 e9" ),
        createKnightLine( "f10 h9" ),
        createKnightLine( "f10 g4" ),
        createKnightLine( "f10 e4" ),
        createKnightLine( "f10 i9" ),
        createKnightLine( "f10 i11" ),
        createKnightLine( "e10 g9" ),
        createKnightLine( "e10 f4" ),
        createKnightLine( "e10 d4" ),
        createKnightLine( "e10 i5" ),
        createKnightLine( "e10 j9" ),
        createKnightLine( "i10 f9" ),
        createKnightLine( "i10 e4" ),
        createKnightLine( "i10 j5" ),
        createKnightLine( "i10 k9" ),
        createKnightLine( "j10 e9" ),
        createKnightLine( "j10 i5" ),
        createKnightLine( "j10 k5" ),
        createKnightLine( "j10 l9" ),
        createKnightLine( "k10 i9" ),
        createKnightLine( "k10 j5" ),
        createKnightLine( "k10 l5" ),
        createKnightLine( "l10 j9" ),
        createKnightLine( "l10 k5" ),
        
        createKnightLine( "h9 g3" ),
        createKnightLine( "h9 f4" ),
        createKnightLine( "g9 h3" ),
        createKnightLine( "g9 f3" ),
        createKnightLine( "g9 e4" ),
        createKnightLine( "f9 h4" ),
        createKnightLine( "f9 g3" ),
        createKnightLine( "f9 e3" ),
        createKnightLine( "f9 d4" ),
        createKnightLine( "f9 i5" ),
        createKnightLine( "e9 g4" ),
        createKnightLine( "e9 f3" ),
        createKnightLine( "e9 d3" ),
        createKnightLine( "e9 j5" ),
        createKnightLine( "i9 f4" ),
        createKnightLine( "i9 d6" ),
        createKnightLine( "i9 j6" ),
        createKnightLine( "i9 k5" ),
        createKnightLine( "j9 d5" ),
        createKnightLine( "j9 e4" ),
        createKnightLine( "j9 i6" ),
        createKnightLine( "j9 k6" ),
        createKnightLine( "j9 l5" ),
        createKnightLine( "k9 i5" ),
        createKnightLine( "k9 j6" ),
        createKnightLine( "k9 l6" ),
        createKnightLine( "l9 j5" ),
        createKnightLine( "l9 k6" ),
        
        createKnightLine( "l8 k6" ),
        createKnightLine( "l8 j7" ),
        createKnightLine( "k8 l6" ),
        createKnightLine( "k8 j6" ),
        createKnightLine( "k8 i7" ),
        createKnightLine( "j8 l7" ),
        createKnightLine( "j8 k6" ),
        createKnightLine( "j8 i6" ),
        createKnightLine( "j8 d7" ),
        createKnightLine( "i8 k7" ),
        createKnightLine( "i8 j6" ),
        createKnightLine( "i8 d6" ),
        createKnightLine( "i8 c7" ),
        createKnightLine( "d8 j7" ),
        createKnightLine( "d8 i6" ),
        createKnightLine( "d8 c6" ),
        createKnightLine( "d8 b7" ),
        createKnightLine( "c8 i7" ),
        createKnightLine( "c8 d6" ),
        createKnightLine( "c8 b6" ),
        createKnightLine( "c8 a7" ),
        createKnightLine( "b8 d7" ),
        createKnightLine( "b8 c6" ),
        createKnightLine( "b8 a6" ),
        createKnightLine( "a8 c7" ),
        createKnightLine( "a8 b6" ),
        
        createKnightLine( "l7 k5" ),
        createKnightLine( "l7 j6" ),
        createKnightLine( "k7 l5" ),
        createKnightLine( "k7 j5" ),
        createKnightLine( "k7 i6" ),
        createKnightLine( "j7 l6" ),
        createKnightLine( "j7 k5" ),
        createKnightLine( "j7 i5" ),
        createKnightLine( "j7 d6" ),
        createKnightLine( "i7 k6" ),
        createKnightLine( "i7 j5" ),
        createKnightLine( "i7 d5" ),
        createKnightLine( "i7 c6" ),
        createKnightLine( "d7 j6" ),
        createKnightLine( "d7 i5" ),
        createKnightLine( "d7 c5" ),
        createKnightLine( "d7 b6" ),
        createKnightLine( "c7 i6" ),
        createKnightLine( "c7 d5" ),
        createKnightLine( "c7 b5" ),
        createKnightLine( "c7 a6" ),
        createKnightLine( "b7 d6" ),
        createKnightLine( "b7 c5" ),
        createKnightLine( "b7 a5" ),
        createKnightLine( "a7 c6" ),
        createKnightLine( "a7 b5" ),
        
        createKnightLine( "l6 k9" ),
        createKnightLine( "l6 j5" ),
        createKnightLine( "k6 l9" ),
        createKnightLine( "k6 j9" ),
        createKnightLine( "k6 i5" ),
        createKnightLine( "j6 l5" ),
        createKnightLine( "j6 k9" ),
        createKnightLine( "j6 i9" ),
        createKnightLine( "j6 d5" ),
        createKnightLine( "i6 k5" ),
        createKnightLine( "i6 j9" ),
        createKnightLine( "i6 e9" ),
        createKnightLine( "i6 d4" ),
        createKnightLine( "i6 c5" ),
        createKnightLine( "d6 j5" ),
        createKnightLine( "d6 i9" ),
        createKnightLine( "d6 e4" ),
        createKnightLine( "d6 c4" ),
        createKnightLine( "d6 b5" ),
        createKnightLine( "c6 i5" ),
        createKnightLine( "c6 d4" ),
        createKnightLine( "c6 b4" ),
        createKnightLine( "c6 a5" ),
        createKnightLine( "b6 d5" ),
        createKnightLine( "b6 c4" ),
        createKnightLine( "b6 a4" ),
        createKnightLine( "a6 c5" ),
        createKnightLine( "a6 b4" ),
                
        createKnightLine( "l5 k10" ),
        createKnightLine( "l5 j9" ),
        createKnightLine( "k5 l10" ),
        createKnightLine( "k5 j10" ),
        createKnightLine( "k5 i9" ),
        createKnightLine( "j5 l9" ),
        createKnightLine( "j5 k10" ),
        createKnightLine( "j5 i10" ),
        createKnightLine( "j5 e9" ),
        createKnightLine( "j5 d4" ),
        createKnightLine( "i5 k9" ),
        createKnightLine( "i5 j10" ),
        createKnightLine( "i5 e10" ),
        createKnightLine( "i5 c4" ),
        createKnightLine( "d5 j9" ),
        createKnightLine( "d5 e3" ),
        createKnightLine( "d5 c3" ),
        createKnightLine( "d5 b4" ),
        createKnightLine( "c5 i9" ),
        createKnightLine( "c5 e4" ),
        createKnightLine( "c5 d3" ),
        createKnightLine( "c5 b3" ),
        createKnightLine( "c5 a4" ),
        createKnightLine( "b5 d4" ),
        createKnightLine( "b5 c3" ),
        createKnightLine( "b5 a3" ),
        createKnightLine( "a5 c4" ),
        createKnightLine( "a5 b3" )

    );
}


